import type { Metadata } from 'next';

import './globals.css';
import { onest } from '@/config/font';
import { Providers } from '@/components/providers/Providers';
import { Toaster } from '@/components/ui/sonner';

export const metadata: Metadata = {
  title: 'next-auth',
  description: 'Generated by appncy',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={onest.className}>
        <Providers>
          <Toaster />
          {children}
        </Providers>
      </body>
    </html>
  );
}
